---
layout: post
title: "Краевые ситуации при разработке ПО"
date: 2011-04-13
comments: false
categories:
 - bug
 - prestashop-sync
---


Сегодня первый человек наконец-то воспользовался формой обратной связи с  разработчиком сервиса (то есть со мной) и сообщил о том, что сервис для  него не работает.
Ошибка была интересной и неочевидной, и мне потребовалось некоторое время на её исправление.
Дело  в том, что мой сервис получает данные от PHP-скрипта на стороне  интернет-магазина, представляющего собой некоторое упрощённое API для  сервиса на Python/Django.
Так вот, этот PHP-скрипт на выходе выдаёт  данные в JSON-формате, которые затем преобразуются в коде Python  обратно. При этом в PHP нет различия по типу между списком и именованным  списом, а в Python это два разных типа - list и dict соответственно. И  когда я на принимающей стороне считал что-то типом dict, а значение этой  переменной в JSON было пустым, то оно конвертировалось в list, а не в  dict, из-за этого метода проверки на наличие ключа в переменной без  проверки на непустоту переменной вызывал исключение.
Такие дела.
